# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/test

name: COBOL / Test (Windows)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Cache GnuCOBOL
        id: cache-gnu-cobol
        uses: actions/cache@v3
        with:
          path: ~\gnucobol-3.2-dev.zip
          key: ${{ runner.os }}-gnu-cobol-3.2

      - name: Install GnuCOBOL
        if: steps.cache-gnu-cobol.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          choco install gnucobol
          
      - name: Run tests for all exercises
        shell: pwsh
        run: |
          $env:Path = "C:\ProgramData\chocolatey\lib\gnucobol\bin;" + $env:Path
          [System.Environment]::SetEnvironmentVariable('COB_CONFIG_DIR', 'C:\ProgramData\chocolatey\lib\gnucobol\config')
          [System.Environment]::SetEnvironmentVariable('COB_COPY_DIR', 'C:\ProgramData\chocolatey\lib\gnucobol\copy')
          [System.Environment]::SetEnvironmentVariable('COB_CFLAGS', '-I C:\ProgramData\chocolatey\lib\gnucobol\include')
          [System.Environment]::SetEnvironmentVariable('COB_LDFLAGS', '-L C:\ProgramData\chocolatey\lib\gnucobol\lib')
          [System.Environment]::SetEnvironmentVariable('COB_LIBRARY_PATH', 'C:\ProgramData\chocolatey\lib\gnucobol\lib')
          [System.Environment]::SetEnvironmentVariable('COB_LIBS', 'C:\ProgramData\chocolatey\lib\gnucobol\bin\libcob-4.dll')
          bin/test.ps1
